# Naive Bayes Project Tutorial
 
This is a simple project using Naive Bayes Classifier and Scikit-learn to create a Google Play store reviews classifier (Sentiment Analysis) in Python. You will categorize user reviews as good or bad. The Naive Bayes classification technique is a simple and powerful classification task in machine learning. The Naive Bayes classification technique is a simple and powerful classification task in machine learning. In this dataset, we use the 23 most popular mobile apps, and only two columns.

## Import Library

In [4]:
!pip install pandas
!pip install nltk
!pip install sklearn


[notice] A new release of pip available: 22.1.2 -> 22.2
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip available: 22.1.2 -> 22.2
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip available: 22.1.2 -> 22.2
[notice] To update, run: pip install --upgrade pip


In [5]:
import pandas as pd
import numpy as np

import nltk #text processing
import re
import unicodedata
from nltk.corpus import stopwords

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
 

In [6]:
#load the words to use as filter
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /home/gitpod/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

## Load Data of Reviews

In [7]:
df = pd.read_csv('https://raw.githubusercontent.com/4GeeksAcademy/naive-bayes-project-tutorial/main/playstore_reviews_dataset.csv')

In [8]:
df.head()

package_name                                             review  \
0  com.facebook.katana   privacy at least put some option appear offli...   
1  com.facebook.katana   messenger issues ever since the last update, ...   
2  com.facebook.katana   profile any time my wife or anybody has more ...   
3  com.facebook.katana   the new features suck for those of us who don...   
4  com.facebook.katana   forced reload on uploading pic on replying co...   

   polarity  
0         0  
1         0  
2         0  
3         0  
4         0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   package_name  891 non-null    object
 1   review        891 non-null    object
 2   polarity      891 non-null    int64 
dtypes: int64(1), object(2)
memory usage: 21.0+ KB


In [10]:
#package name, review and polarity (0 = bad, 1 = good) 

In [11]:
df.head()

package_name                                             review  \
0  com.facebook.katana   privacy at least put some option appear offli...   
1  com.facebook.katana   messenger issues ever since the last update, ...   
2  com.facebook.katana   profile any time my wife or anybody has more ...   
3  com.facebook.katana   the new features suck for those of us who don...   
4  com.facebook.katana   forced reload on uploading pic on replying co...   

   polarity  
0         0  
1         0  
2         0  
3         0  
4         0

In [12]:
df['polarity'].value_counts()

0    584
1    307
Name: polarity, dtype: int64

## Text Processing - Clean

### Step 1 - chante all to lower case

In [13]:
#Preprocess the data by eliminating the package name column and putting all reviews in lower case.

df.drop(['package_name'],axis=1, inplace=True)
#chante all to lower case
df['review'] = df['review'].str.lower()

### Step 2 - Remove all words that not have meaning to the search - stop words

In [14]:

#see, the word in the reviews, create a list of word and frecuency
df['review'].str.split(expand = True).stack().value_counts()[:60] #(show top 60)

the       1293
to        1159
i         1084
and        853
it         778
a          619
is         555
my         442
this       421
for        410
of         390
but        348
in         340
on         325
not        318
app        317
you        315
that       260
have       252
with       220
so         203
be         194
no         186
when       182
if         180
or         169
all        163
can        158
as         148
me         145
are        139
it's       138
can't      137
update     136
new        136
like       135
fix        133
please     131
good       128
game       121
one        119
use        118
just       117
get        112
its        111
very       109
more       107
was        104
there      104
don't      103
now        102
will       102
even       101
from       101
at         100
up          99
great       99
time        93
your        90
do          89
dtype: int64

In [15]:
#remove the stopword
stop = stopwords.words('english')

def remove_stopwords(text):
  if text is not None:
    #list of the word in the text
    words = text.strip().split()
    words_filtered = []
    for word in words:
      if word not in stop:
        words_filtered.append(word)
    result = " ".join(words_filtered) #join the word in a text with space separation
  else:
      result = None
  return result

In [16]:
df_interim = df.copy()

In [17]:
df_interim['review'] = df_interim['review'].apply(remove_stopwords)

In [18]:
df_interim['review'].str.split(expand=True).stack().value_counts()[:60] 

app         317
can't       137
new         136
update      136
like        135
fix         133
please      131
good        128
game        121
one         119
use         118
get         112
even        101
great        99
time         93
really       82
would        80
back         78
still        78
love         77
browser      76
make         74
see          69
using        68
work         67
i'm          67
5            67
open         65
want         64
it.          64
google       63
much         61
phone        61
every        61
u            58
option       58
version      57
go           56
way          56
app.         56
used         55
also         55
android      54
download     53
best         52
.            51
give         50
better       50
play         50
send         49
people       48
able         47
message      47
since        46
many         45
keep         45
works        44
i've         44
old          43
find         43
dtype: int64

In [19]:
def word_only_letters(word):
    for c in word:
        cat = unicodedata.category(c)
        if cat not in ('Ll','Lu'):  #only letter upper y lower
            return False
    return True

# clean only letter
def text_only_letters(text):
    if text is not None:
        #list of the word in the text
        words = text.strip().split()
        words_filtered = []
        for word in words:
            if word_only_letters(word):
                words_filtered.append(word)
            result = " ".join(words_filtered) #join the word in a text with space separation
    else:
        result = None
    return result



In [20]:
df_interim['review'] = df_interim['review'].apply(text_only_letters)

In [21]:
#remove multi letter looove iiiitttt, or repeat secuence
def replace_multiple_letters(message):
  if message is not None:
    result = re.sub(r'(.+?)\1+', r'\1', message)
    #result = re.sub(r"([a-zA-Z])＼1{2,}", r"＼1", message)
  else:
    result = None
  return result

In [22]:
df_interim['review'] = df_interim['review'].apply(replace_multiple_letters)

In [23]:
df_interim['review']

0      privacy least put option apear mean people lik...
1      mesenger isues ever since last initial receive...
2      profile time wife anybody one post view would ...
3      new features suck us working back buton guys m...
4      forced reload uploading pic replying coment la...
                             ...                        
886    loved loved incredible awesome go power make n...
887    time legendary game birthday party levels shor...
888    ads way heavy listen bad ads every whether pas...
889        fun works perfectly ads anoying especialy fre
890    everywhere se angry birds everywhere stop play...
Name: review, Length: 891, dtype: object

In [24]:
#copy to df
df = df_interim.copy()

### Setp 3 - Model

In [25]:
# Separate target and predictor
X = df['review']
y = df['polarity']

In [26]:
#Split your data in train and test set
X_train, X_test, y_train, y_test = train_test_split(X,y, stratify=y, random_state=42) #, test_size=0.25

In [27]:
#Vectorizer change matriz with 0-1
vec = CountVectorizer(stop_words = "english")
X_train = vec.fit_transform(X_train).toarray()
X_test = vec.transform(X_test).toarray()

In [28]:
X_train

array([[1, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0]])

In [29]:
X_train.shape

(668, 2636)

In [30]:
vec.get_feature_names_out()

array(['ability', 'abke', 'able', ..., 'zom', 'zoming', 'ìs'],
      dtype=object)

In [31]:
#Naive Bayes
nb = MultinomialNB()
nb.fit(X_train, y_train)

MultinomialNB()

In [32]:
#score of train dataset 
nb.score(X_train, y_train)

0.9431137724550899

In [33]:
#score test dataset
nb.score(X_test, y_test)

0.8116591928251121

In [34]:
nb.predict(vec.transform(['i don\'t like','eat much ram','eat','like']))


array([0, 0, 0, 0])

In [35]:
nb.predict(vec.transform(['love','great solid love important feature','ram','like fast']))

array([1, 1, 0, 1])

In [36]:
df[df['polarity']==1]['review'].sample(10)

800    great one problem ruins love firefox fast adon...
691    briliant complete please ad posible themes u n...
825                                         god one best
853    god great god chalenges something easily wip k...
743    great simple great aps news always used read n...
584    one best aps ever first bit skeptical got used...
170    amazing game awesome game entertaing ap favori...
500    useful thank god finaly reply faster thanks up...
661    hamro nepali keyboard best keyboard fluent nep...
182                  prety god say oh wait fun game play
Name: review, dtype: object

In [37]:
df[df['polarity']==0]['review'].sample(10)

699    cant download big things cant download mb says...
436    privacy nice works agenda smartphone think mig...
6      major flaws constant updates always geting ins...
309    video capture moment video moment want capture...
447    simply god think los reply option keps people ...
20     whenever post update try edit hit save tels po...
187    god game always liked temple run however new u...
335    please fix new version sems canot open viber t...
566                     log checked credentials multiple
100    star backward redesign ap design perfectly ade...
Name: review, dtype: object